export default function Head () {
  return (
    <>
      <title>Monkey Records - Sello discografico Montería</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/Monkey_records.ico' />
      <base href='/' />
    </>
  )
}
